version: '3'
services:
  db:
    container_name: postgersql
    image: postgres
    restart: on-failure
    ports:
      - '5438:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
